### ISSUE TITLE
Plant Disease segmentation using parallel programming using python ray 

### ISSUE THREAD

**Issue by 04dhanushn** [kishorekumar0814/Plant-Disease-Segmentation-Using-Parallel-Image-Processing-with-Python-Ray#1]
In requirements of packages there is not specified any versions that we have to install.

**Comment by kishorekumar0814** [comment]
The requirements.txt file has been updated to include the necessary packages for both the parallel and sequential processing codes. The requirements for the sequential processing code have also been included in the updated seq_requirements.txt file. I hope now  the issue will be resolved!
